# Generated by Django 3.1.4 on 2020-12-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20201230_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
    ]
